#namespace enjin.sdk.shared.Wallet
#import enjin.sdk.shared.Asset
#import enjin.sdk.shared.Balance
#import enjin.sdk.shared.Transaction

#arg walletBalanceFilter BalanceFilter
#arg withAssetsCreated Boolean false
#arg withWalletBalances Boolean false
#arg withWalletTransactions Boolean false

fragment Wallet on Wallet {
    ethAddress
    enjAllowance
    enjBalance
    ethBalance
    assetsCreated @include(if: $withAssetsCreated) {
        ...Asset
    }
    balances(filter: $walletBalanceFilter) @include(if: $withWalletBalances) {
        ...Balance
    }
    transactions @include(if: $withWalletTransactions) {
        ...Transaction
    }
}
