fragment TokenEventFragment on EnjinTokenEvent {
    id
    tokenId
    event
    param1 @include(if: $withEventParams)
    param2 @include(if: $withEventParams)
    param3 @include(if: $withEventParams)
    param4 @include(if: $withEventParams)
    blockNumber @include(if: $withBlockNumber)
    token @include(if: $withEventToken) {
        ...TokenFragment
    }
    createdAt @include(if: $withTokenEventTimestamps)
    updatedAt @include(if: $withTokenEventTimestamps)
}

$withEventParams: Boolean = true
$withBlockNumber: Boolean = true
$withEventToken: Boolean = false
$withTokenEventTimestamps: Boolean = false