mutation {
    result: CreateEnjinRequest(
        appId: $appId,
        ethAddress: $ethAddr,
        identityId: $identityId,
        type: $txType,
        test: $test,
        dummy: $dummy,
        create_token_data: $createTokenData,
        create_trade_data: $createTradeData,
        complete_trade_data: $completeTradeData,
        mint_token_data: $mintTokenData,
        melt_token_data: $meltTokenData,
        send_token_data: $sendTokenData,
        send_enj_data: $sendEnjData,
        advanced_send_token_data: $advancedSendTokenData,
        update_item_name_data: $updateItemNameData,
        set_item_uri_data: $setItemUriData,
        set_whitelisted_data: $setWhitelistedData,
        approve_enj_data: $approveEnjData,
        approve_item_data: $approveItemData,
        set_transferable_data: $setTransferableData,
        set_melt_fee_data: $setMeltFeeData,
        decrease_max_melt_fee_data: $decreaseMaxMeltFeeData,
        set_transfer_fee_data: $setTransferFeeData,
        decrease_max_transfer_fee_data: $decreaseMaxTransferFeeData,
        release_reserve_data: $releaseReserveData,
        add_log_data: $addLogData,
        set_approval_for_all_data: $setApprovalForAllData,
        message_data: $messageData
    ) {
        ...TransactionFragment
    }
}

$appId: Int
$ethAddr: String
$identityId: Int
$txType: TransactionType
$test: Boolean
$dummy: Boolean
$createTokenData: CreateTokenInput
$createTradeData: CreateTradeInput
$completeTradeData: CompleteTradeInput
$mintTokenData: MintTokenInput
$meltTokenData: MeltTokenInput
$sendTokenData: SendTokenInput
$sendEnjData: SendEnjInput
$advancedSendTokenData: AdvancedSendTokenInput
$updateItemNameData: UpdateItemNameInput
$setItemUriData: SetItemUriInput
$setWhitelistedData: SetWhitelistedInput
$approveEnjData: ApproveEnjInput
$approveItemData: ApproveItemInput
$setTransferableData: SetTransferableInput
$setMeltFeeData: SetMeltFeeInput
$decreaseMaxMeltFeeData: DecreaseMaxMeltFeeInput
$setTransferFeeData: SetTransferFeeInput
$decreaseMaxTransferFeeData: DecreaseMaxTransferFeeInput
$releaseReserveData: ReleaseReserveInput
$addLogData: AddLogInput
$setApprovalForAllData: SetApprovalForAllInput
$messageData: MessageInput
