#namespace enjin.sdk.project.AuthProject

#arg uuid String!
#arg secret String!

query {
    result: AuthProject(
        uuid: $uuid,
        secret: $secret
    ) {
        accessToken
        expiresIn
    }
}
