#namespace enjin.sdk.project.GetWallet
#import enjin.sdk.shared.Wallet

#arg userId String
#arg ethAddress EthAddress

query {
    result: GetWallet(
        userId: $userId
        ethAddress: $ethAddress
    ) {
        ...Wallet
    }
}
