#namespace enjin.sdk.shared.GetTransaction
#import enjin.sdk.shared.Transaction

#arg id Int
#arg transactionId String

query {
    result: GetTransaction(
        id: $id,
        transactionId: $transactionId
    ) {
        ...Transaction
    }
}
