#namespace enjin.sdk.shared.GetTransactions
#import enjin.sdk.shared.Transaction
#import enjin.sdk.shared.PaginationCursor

#arg filter TransactionFilter
#arg sort TransactionSortInput {field:created_at,direction:asc}
#arg pagination PaginationInput {page:1,limit:100}

query {
    result: GetTransactions(
        filter: $filter
        sort: $sort
        pagination: $pagination
    ) {
        items {
            ...Transaction
        }
        cursor {
            ...PaginationCursor
        }
    }
}
