name: Tests

on:
  push:
    branches:
      - master
  pull_request:

permissions: read-all

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run Tests
        run: |
          chmod +x ./gradlew
          ./gradlew :sdk:test -D test.ignoreFailures=false clean build
