name: unit_tests

on:
  push:
    branches:
      - master
  pull_request:

permissions: read-all

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Generate
        run: |
          chmod +x ./gradlew
          ./gradlew :sdk:test
